[package]
name = "widget"
version = "0.1.0"
edition = "2021"

[dependencies]
winsafe = { version = "0.0.26", features = ["gdi"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_precision_loss = "allow"
